[package]
name = "gt-adapter-http"
description = "axum HTTP inbound adapter"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
gt-domain = { workspace = true }
anyhow = { workspace = true }
gt-application = { workspace = true }
axum = { workspace = true }
tokio = { workspace = true }
tower-http = { workspace = true, features = ["fs", "util", "cors", "trace"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
gt-adapter-sqlite = { workspace = true }
gt-adapter-fs = { workspace = true }
gt-adapter-parser = { workspace = true }
gt-adapter-fkb = { workspace = true }
gt-adapter-rules = { workspace = true }
gt-adapter-views = { workspace = true }
gt-adapter-techstack = { workspace = true }
tower = { workspace = true }
