//! Strongly typed identifiers.
//!
//! Newtypes distinguish the primary keys of different entities, so mistakes like "passing a FileId where a NodeId is
//! expected" are caught at compile time. Every ID is an `i64` underneath, matching SQLite's `INTEGER PRIMARY KEY`.

/// Generated by a macro: an `i64` newtype plus the common traits.
macro_rules! declare_ids {
    ($( $(#[$meta:meta])* $name:ident => $doc:literal ),* $(,)?) => {
        $(
            $(#[$meta])*
            #[doc = $doc]
            #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, serde::Serialize, serde::Deserialize, Default)]
            pub struct $name(pub i64);

            impl $name {
                /// The empty sentinel (not persisted).
                pub const NONE: $name = $name(0);

                pub fn new(v: i64) -> Self { Self(v) }
                pub fn get(self) -> i64 { self.0 }
                pub fn is_none(self) -> bool { self.0 == 0 }
            }

            impl std::fmt::Display for $name {
                fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                    write!(f, "{}", self.0)
                }
            }

            impl From<i64> for $name {
                fn from(v: i64) -> Self { Self(v) }
            }

            impl From<$name> for i64 {
                fn from(v: $name) -> Self { v.0 }
            }
        )*
    };
}

declare_ids! {
    ProjectId    => "project (the top-level codebase being analysed)",
    SubProjectId => "sub-project (an independently analysable unit inside a project, e.g. backend / the uni-app frontend)",
    FileId       => "source file",
    NodeId       => "graph node",
    EdgeId       => "graph edge",
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The two invariants the macro cannot state itself, but that callers silently rely on.
    ///
    /// Everything else the macro generates (`new` / `get` / `From` / `Display` / `Ord`) is guaranteed by
    /// the derives — the one thing a test *cannot* cover is "a `FileId` never reaches a `NodeId` slot",
    /// which is a compile-time property.
    #[test]
    fn default_is_the_none_sentinel_and_ids_serialize_as_bare_integers() {
        // `Default` is derived while `NONE` is hand-written, so nothing keeps them in sync: if either
        // moved, "a default-constructed id" would stop meaning "no id".
        assert_eq!(NodeId::default(), NodeId::NONE);
        assert_eq!(NodeId::default().get(), 0);
        assert!(NodeId::default().is_none());
        assert_eq!(SubProjectId::default(), SubProjectId::NONE);
        assert!(!NodeId::new(1).is_none());

        // A newtype serialises **transparently** (`42`, not `{"0": 42}`) — persisted ids and API
        // responses depend on that shape.
        assert_eq!(
            serde_json::to_value(NodeId(42)).unwrap(),
            serde_json::json!(42)
        );
        let back: NodeId = serde_json::from_value(serde_json::json!(42)).unwrap();
        assert_eq!(back, NodeId(42));
    }
}
