//! Strongly typed identifiers.
//!
//! Newtypes distinguish the primary keys of different entities, so mistakes like "passing a FileId where a NodeId is
//! expected" are caught at compile time. Every ID is an `i64` underneath, matching SQLite's `INTEGER PRIMARY KEY`.

/// Generated by a macro: an `i64` newtype plus the common traits.
macro_rules! declare_ids {
    ($( $(#[$meta:meta])* $name:ident => $doc:literal ),* $(,)?) => {
        $(
            $(#[$meta])*
            #[doc = $doc]
            #[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, serde::Serialize, serde::Deserialize, Default)]
            pub struct $name(pub i64);

            impl $name {
                /// The empty sentinel (not persisted).
                pub const NONE: $name = $name(0);

                pub fn new(v: i64) -> Self { Self(v) }
                pub fn get(self) -> i64 { self.0 }
                pub fn is_none(self) -> bool { self.0 == 0 }
            }

            impl std::fmt::Display for $name {
                fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                    write!(f, "{}", self.0)
                }
            }

            impl From<i64> for $name {
                fn from(v: i64) -> Self { Self(v) }
            }

            impl From<$name> for i64 {
                fn from(v: $name) -> Self { v.0 }
            }
        )*
    };
}

declare_ids! {
    ProjectId    => "project (the top-level codebase being analysed)",
    SubProjectId => "sub-project (an independently analysable unit inside a project, e.g. backend / the uni-app frontend)",
    FileId       => "source file",
    NodeId       => "graph node",
    EdgeId       => "graph edge",
}
